source 'https://api.berkshelf.com'
cookbook 'chef-solo-search', '~> 0.5.1'
cookbook 'build-essential'
cookbook 'openssl', '~> 4.0.0'
cookbook 'geoshapeosm', '~> 0.0.6', path: 'cookbooks/geoshapeosm'
cookbook 'fail2ban', '~> 2.2.1'
