source 'https://api.berkshelf.com'
cookbook 'chef-solo-search', '~> 0.5.1'
cookbook 'build-essential'
cookbook 'openssl', '~> 4.0.0'
cookbook 'geoshapeosm', '~> 1.0.0', path: 'cookbooks/geoshapeosm'
cookbook 'fail2ban', '~> 2.2.1'
