name             'rogue'
description      'Installs/Configures the ROGUE JCTD project'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.2'

depends 'apt', '~> 2.2'
depends 'build-essential', '~> 2.0.0'
depends 'git', '~> 2.6.0'
depends 'python', '~> 1.4.2'
depends 'ohai', '~> 2.0'
depends 'hostsfile', '~> 2.4.1'
depends 'java','~> 1.22.0'
depends 'supervisord', '~> 1.0.1'
depends 'runit','~> 1.5.10'
depends 'rabbitmq', '~> 3.6.0'
depends 'openssl', '~> 2.0.2'
depends 'postgres', '~> 2.11.0'
depends 'postgis', '~> 0.3.0'
depends 'database', '~> 4.0.6'
