name             'apt'
maintainer       'JAM'
license          'Apache 2.0'
description      'Configures postgres'
version          '0.1.0'

#depends 'apt', '~> 2.7.0'
#depends 'postgresql', '~> 3.4.18'
#depends 'database', '~> 4.0.5'
depends 'postgresql'
