default['db_name'] = 'osm'
default['db_admin_name'] = 'osmdata'
default['db_render_name'] = 'osmrender'
default['db_password'] = '$1$ngB3EurO$i9SlxPxJoSUPhcLkYqcFm0'
default['db_admin_password'] = '\'$1$HdgDew2V$KwNn98bP9tHgUpbsNSGAR0\''
